baseURL = 'https://yggdrasil-917.github.io/'
languageCode = 'en-us'
title = 'Tempest Engine Dev'
theme = 'hermit-v2'

pygmentsCodefences  = true
pygmentsUseClasses  = true

enableEmoji = true

[taxonomies]
  tag = "tags"
  
[services]
  [services.disqus]
    shortname = ''

[frontmatter]
  date = ["date", "publishDate", "lastmod"]
  lastmod = ["lastmod", ":git", "date", "publishDate"]
  publishDate = ["publishDate", "date"]
  expiryDate = ["expiryDate"]

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  homeSubtitle = "Engine programming and other related things."
  footerCopyright = "XGH"
  shareSocial = true
  readTime = true
  
  themeColor = "#494f5c"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/yggdrasil-917"
    
  [[params.socialLinks]]
    name = "email"
    url = "yggdrasil.917@gmail.com"

[menu]
  
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about"
    weight = 20
    